import { neon } from "@neondatabase/serverless";
import { readFileSync } from "fs";
const envFile = readFileSync(".env.local", "utf8");
for (const line of envFile.split("\n")) { const m = line.match(/^([^#][^=]*)=(.*)$/); if (m) process.env[m[1].trim()] = m[2].trim(); }
const sql = neon(process.env.DATABASE_URL);

async function upsertIndustry(ind) {
  const existing = await sql`SELECT id FROM industries WHERE slug=${ind.slug} LIMIT 1`;
  let id;
  if (existing.length > 0) {
    id = existing[0].id;
    await sql`UPDATE industries SET name=${ind.name},sort_order=${ind.so},short_description=${ind.sd},hero_eyebrow=${ind.he},hero_heading=${ind.hh},hero_description=${ind.hd},hero_image_url=${ind.hiu},hero_image_alt=${ind.hia},hero_cta1_text=${ind.hc1t},hero_cta1_href=${ind.hc1h},hero_cta2_text=${ind.hc2t},hero_cta2_href=${ind.hc2h},overview_heading=${ind.oh},overview_quote=${ind.oq},overview_body=${ind.ob},overview_body2=${ind.ob2},challenges_intro=${ind.ci},solutions_heading=${ind.sh},solutions_intro=${ind.si},final_cta_heading=${ind.fch},final_cta_description=${ind.fcd},final_cta1_text=${ind.fc1t},final_cta1_href=${ind.fc1h},final_cta2_text=${ind.fc2t},final_cta2_href=${ind.fc2h},is_published=true,updated_at=NOW() WHERE id=${id}`;
  } else {
    const [r] = await sql`INSERT INTO industries (slug,name,sort_order,short_description,hero_eyebrow,hero_heading,hero_description,hero_image_url,hero_image_alt,hero_cta1_text,hero_cta1_href,hero_cta2_text,hero_cta2_href,overview_heading,overview_quote,overview_body,overview_body2,challenges_intro,solutions_heading,solutions_intro,final_cta_heading,final_cta_description,final_cta1_text,final_cta1_href,final_cta2_text,final_cta2_href,is_published) VALUES (${ind.slug},${ind.name},${ind.so},${ind.sd},${ind.he},${ind.hh},${ind.hd},${ind.hiu},${ind.hia},${ind.hc1t},${ind.hc1h},${ind.hc2t},${ind.hc2h},${ind.oh},${ind.oq},${ind.ob},${ind.ob2},${ind.ci},${ind.sh},${ind.si},${ind.fch},${ind.fcd},${ind.fc1t},${ind.fc1h},${ind.fc2t},${ind.fc2h},true) RETURNING id`;
    id = r.id;
  }
  await sql`DELETE FROM industry_challenges WHERE industry_id=${id}`;
  for (let i=0;i<ind.ch.length;i++) { const c=ind.ch[i]; await sql`INSERT INTO industry_challenges (industry_id,number,title,description,sort_order,is_visible) VALUES (${id},${c.n},${c.t},${c.d},${i},true)`; }
  await sql`DELETE FROM industry_solutions WHERE industry_id=${id}`;
  for (let i=0;i<ind.sol.length;i++) { const s=ind.sol[i]; await sql`INSERT INTO industry_solutions (industry_id,label,description,sort_order,is_visible) VALUES (${id},${s.l},${s.d},${i},true)`; }
  const pas = await sql`SELECT id,slug FROM practice_areas WHERE is_published=true`;
  const paMap = Object.fromEntries(pas.map(p=>[p.slug,p.id]));
  await sql`DELETE FROM industry_practice_areas WHERE industry_id=${id}`;
  for (let i=0;i<ind.pas.length;i++) { const paId=paMap[ind.pas[i]]; if (paId) await sql`INSERT INTO industry_practice_areas (industry_id,practice_area_id,sort_order) VALUES (${id},${paId},${i}) ON CONFLICT DO NOTHING`; }
  console.log("  seeded: " + ind.name + " (id=" + id + ")");
}

const industries = [
  {slug:"healthcare",name:"Healthcare",so:7,sd:"Balancing clinical innovation with operational governance.",he:"INDUSTRIES",hh:"Healthcare Advisory",hd:"Balancing clinical innovation with operational governance for healthcare providers navigating patient safety mandates and financing pressure.",hiu:"https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=1200&q=85",hia:"Healthcare facility",hc1t:"TALK TO OUR INDUSTRY EXPERTS",hc1h:"/contact",hc2t:"EXPLORE RELEVANT SERVICES",hc2h:"/industries/healthcare#how-we-help",oh:"Understanding Healthcare",oq:"Healthcare governance must satisfy patient safety obligations and financial sustainability simultaneously — neither can be sacrificed.",ob:"The healthcare sector is defined by dense clinical regulation, rising operational costs, and the ongoing pressure to modernize care delivery.",ob2:"Our teams bring applied experience in healthcare compliance, provider financing, and the operational restructuring of clinical organizations.",ci:"Strategic imperatives dictated by the current healthcare regulatory and cost environment.",sh:"Advisory Built Around Patient-Centered Governance",si:"We deploy cross-functional teams combining healthcare compliance knowledge with operational finance expertise.",fch:"Lets Discuss Your Healthcare Strategy.",fcd:"Schedule a confidential consultation with our sector specialists.",fc1t:"TALK TO OUR INDUSTRY EXPERTS",fc1h:"/contact",fc2t:"BOOK A CONSULTATION",fc2h:"/book-consultation",ch:[{n:"01.",t:"Clinical Compliance",d:"Navigating dense patient safety and data privacy mandates across care settings."},{n:"02.",t:"Cost Pressure",d:"Managing rising operational costs against constrained reimbursement models."},{n:"03.",t:"Digital Health Integration",d:"Structuring governance for telehealth and digital care delivery expansion."},{n:"04.",t:"Workforce Sustainability",d:"Addressing clinical staffing shortages through operational and financial restructuring."}],sol:[{l:"NAVIGATE",d:"Clinical compliance and data privacy mandates."},{l:"STRENGTHEN",d:"Governance frameworks for patient safety."},{l:"TRANSFORM",d:"Care delivery through digital integration."},{l:"SCALE",d:"Provider networks through structured capital."}],pas:["risk-assurance","tax-fiscal-advisory","corporate-law","business-advisory"]},
  {slug:"ngos",name:"NGOs",so:8,sd:"Ensuring transparency and impact in global development.",he:"INDUSTRIES",hh:"NGO Advisory",hd:"Ensuring transparency, accountability, and lasting impact for non-governmental organizations operating across complex jurisdictions.",hiu:"https://images.unsplash.com/photo-1593113646773-028c64a8f1b8?auto=format&fit=crop&w=1200&q=85",hia:"NGO operations",hc1t:"TALK TO OUR INDUSTRY EXPERTS",hc1h:"/contact",hc2t:"EXPLORE RELEVANT SERVICES",hc2h:"/industries/ngos#how-we-help",oh:"Understanding NGOs",oq:"Donor trust is built on transparent governance — the moment it slips, funding follows.",ob:"The NGO sector is defined by donor accountability requirements, cross-border operational complexity, and the need to demonstrate measurable impact.",ob2:"Our teams bring applied experience in nonprofit compliance, grant structuring, and the operational governance unique to mission-driven organizations.",ci:"Strategic imperatives dictated by the current nonprofit governance and funding environment.",sh:"Advisory Built Around Mission-Driven Governance",si:"We deploy cross-functional teams combining nonprofit compliance knowledge with financial governance expertise.",fch:"Lets Discuss Your NGO Strategy.",fcd:"Schedule a confidential consultation with our sector specialists.",fc1t:"TALK TO OUR INDUSTRY EXPERTS",fc1h:"/contact",fc2t:"BOOK A CONSULTATION",fc2h:"/book-consultation",ch:[{n:"01.",t:"Donor Accountability",d:"Structuring financial reporting frameworks that satisfy institutional and individual donor requirements."},{n:"02.",t:"Cross-Border Operations",d:"Navigating divergent nonprofit registration and tax regimes across operating countries."},{n:"03.",t:"Impact Measurement",d:"Building credible frameworks for demonstrating programmatic outcomes to stakeholders."},{n:"04.",t:"Funding Volatility",d:"Diversifying revenue streams against shifting donor priorities and grant cycles."}],sol:[{l:"NAVIGATE",d:"Cross-border nonprofit registration and tax regimes."},{l:"STRENGTHEN",d:"Donor reporting and governance frameworks."},{l:"TRANSFORM",d:"Impact measurement into credible reporting."},{l:"SCALE",d:"Programs through diversified funding structures."}],pas:["risk-assurance","tax-fiscal-advisory","corporate-law","business-advisory"]},
  {slug:"technology",name:"Technology",so:9,sd:"Scaling digital solutions within legal frameworks.",he:"INDUSTRIES",hh:"Technology Advisory",hd:"Scaling digital solutions within legal frameworks, balancing rapid product iteration against tightening data and platform regulation.",hiu:"https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=85",hia:"Technology innovation",hc1t:"TALK TO OUR INDUSTRY EXPERTS",hc1h:"/contact",hc2t:"EXPLORE RELEVANT SERVICES",hc2h:"/industries/technology#how-we-help",oh:"Understanding Technology",oq:"Technology companies scale fastest when compliance is designed in from the first architecture decision, not bolted on afterward.",ob:"The technology sector is defined by rapid product cycles, intensifying data protection regulation, and increasing scrutiny of platform market power.",ob2:"Our teams bring applied experience in data privacy law, IP protection, and the fiscal structuring unique to high-growth technology enterprises.",ci:"Strategic imperatives dictated by the current technology regulatory environment.",sh:"Advisory Built Around Rapid Compliant Scale",si:"We deploy cross-functional teams combining data privacy expertise with technology-sector fiscal structuring.",fch:"Lets Discuss Your Technology Strategy.",fcd:"Schedule a confidential consultation with our sector specialists.",fc1t:"TALK TO OUR INDUSTRY EXPERTS",fc1h:"/contact",fc2t:"BOOK A CONSULTATION",fc2h:"/book-consultation",ch:[{n:"01.",t:"Data Privacy Regulation",d:"Navigating fragmented global data protection regimes as products scale internationally."},{n:"02.",t:"Platform Scrutiny",d:"Managing antitrust and market power regulation as user bases and market share grow."},{n:"03.",t:"IP Protection",d:"Structuring intellectual property frameworks that hold up under aggressive competitive pressure."},{n:"04.",t:"Talent & Equity Structuring",d:"Building compensation frameworks that attract talent while managing dilution risk."}],sol:[{l:"NAVIGATE",d:"Fragmented global data protection regimes."},{l:"STRENGTHEN",d:"IP protection and governance frameworks."},{l:"TRANSFORM",d:"Compliance into a competitive advantage."},{l:"SCALE",d:"Products through structured capital deployment."}],pas:["risk-assurance","tax-fiscal-advisory","corporate-law","business-advisory"]},
  {slug:"e-commerce",name:"E-Commerce",so:10,sd:"Structuring cross-border retail and logistics.",he:"INDUSTRIES",hh:"E-Commerce Advisory",hd:"Structuring cross-border retail and logistics operations to navigate fragmented tax regimes, consumer protection law, and supply chain complexity.",hiu:"https://images.unsplash.com/photo-1607082349566-187342175e2f?auto=format&fit=crop&w=1200&q=85",hia:"E-commerce logistics",hc1t:"TALK TO OUR INDUSTRY EXPERTS",hc1h:"/contact",hc2t:"EXPLORE RELEVANT SERVICES",hc2h:"/industries/e-commerce#how-we-help",oh:"Understanding E-Commerce",oq:"Cross-border e-commerce succeeds or fails on the fine print of local tax and consumer protection law.",ob:"The e-commerce sector is defined by fragmented indirect tax regimes, tightening consumer protection standards, and logistics complexity at global scale.",ob2:"Our teams bring applied experience in cross-border tax structuring, consumer law, and the logistics governance unique to digital retail operations.",ci:"Strategic imperatives dictated by the current cross-border retail environment.",sh:"Advisory Built Around Global Retail Operations",si:"We deploy cross-functional teams combining cross-border tax expertise with consumer and logistics regulation.",fch:"Lets Discuss Your E-Commerce Strategy.",fcd:"Schedule a confidential consultation with our sector specialists.",fc1t:"TALK TO OUR INDUSTRY EXPERTS",fc1h:"/contact",fc2t:"BOOK A CONSULTATION",fc2h:"/book-consultation",ch:[{n:"01.",t:"Cross-Border Tax",d:"Navigating fragmented VAT, GST, and customs regimes across expansion markets."},{n:"02.",t:"Consumer Protection",d:"Structuring returns, warranty, and disclosure practices that satisfy divergent regional standards."},{n:"03.",t:"Logistics Complexity",d:"Managing fulfillment and last-mile delivery governance across multiple jurisdictions."},{n:"04.",t:"Platform Liability",d:"Structuring marketplace governance to manage third-party seller and product liability exposure."}],sol:[{l:"NAVIGATE",d:"Fragmented VAT, GST, and customs regimes."},{l:"STRENGTHEN",d:"Consumer protection and disclosure practices."},{l:"TRANSFORM",d:"Fulfillment operations for compliant scale."},{l:"SCALE",d:"Markets through structured expansion planning."}],pas:["risk-assurance","tax-fiscal-advisory","corporate-law","business-advisory"]},
  {slug:"media",name:"Media",so:11,sd:"Content rights and digital distribution strategies.",he:"INDUSTRIES",hh:"Media Advisory",hd:"Structuring content rights and digital distribution strategies for media organizations navigating fragmented platforms and shifting monetization models.",hiu:"https://images.unsplash.com/photo-1495020689067-958852a7765e?auto=format&fit=crop&w=1200&q=85",hia:"Media distribution",hc1t:"TALK TO OUR INDUSTRY EXPERTS",hc1h:"/contact",hc2t:"EXPLORE RELEVANT SERVICES",hc2h:"/industries/media#how-we-help",oh:"Understanding Media",oq:"Content rights are the core asset of any media business — and increasingly the hardest thing to protect across platforms.",ob:"The media sector is defined by rights fragmentation across streaming platforms, shifting advertising and subscription economics, and intensifying content licensing complexity.",ob2:"Our teams bring applied experience in IP licensing, digital distribution structuring, and the fiscal planning unique to content-driven businesses.",ci:"Strategic imperatives dictated by the current media distribution environment.",sh:"Advisory Built Around Content Value Protection",si:"We deploy cross-functional teams combining IP licensing expertise with media distribution structuring.",fch:"Lets Discuss Your Media Strategy.",fcd:"Schedule a confidential consultation with our sector specialists.",fc1t:"TALK TO OUR INDUSTRY EXPERTS",fc1h:"/contact",fc2t:"BOOK A CONSULTATION",fc2h:"/book-consultation",ch:[{n:"01.",t:"Rights Fragmentation",d:"Structuring licensing agreements that protect content value across a growing number of distribution platforms."},{n:"02.",t:"Monetization Shifts",d:"Adapting revenue models as advertising and subscription economics continue to evolve."},{n:"03.",t:"Content Compliance",d:"Navigating divergent content regulation and disclosure standards across broadcast markets."},{n:"04.",t:"Platform Dependency",d:"Reducing concentration risk from reliance on a small number of major distribution platforms."}],sol:[{l:"NAVIGATE",d:"Cross-platform content regulation and rights law."},{l:"STRENGTHEN",d:"Licensing and distribution frameworks."},{l:"TRANSFORM",d:"Monetization models for platform diversity."},{l:"SCALE",d:"Distribution through structured partnerships."}],pas:["risk-assurance","tax-fiscal-advisory","corporate-law","business-advisory"]},
  {slug:"startups",name:"Startups",so:12,sd:"Agile advisory for rapid scaling and fundraising.",he:"INDUSTRIES",hh:"Startup Advisory",hd:"Agile advisory for rapid scaling and fundraising, giving founders the governance and financial structure to grow without slowing down.",hiu:"https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=85",hia:"Startup growth",hc1t:"TALK TO OUR INDUSTRY EXPERTS",hc1h:"/contact",hc2t:"EXPLORE RELEVANT SERVICES",hc2h:"/industries/startups#how-we-help",oh:"Understanding Startups",oq:"Startups fail not from lack of ambition but from governance structures that cannot keep pace with growth.",ob:"The startup landscape is defined by compressed fundraising timelines, evolving governance expectations from investors, and the constant tension between speed and structure.",ob2:"Our teams bring applied experience in venture financing structures, cap table management, and the fiscal planning unique to high-growth early-stage companies.",ci:"Strategic imperatives dictated by the current venture financing environment.",sh:"Advisory Built Around Founder-Led Growth",si:"We deploy cross-functional teams combining venture financing expertise with lightweight governance structuring.",fch:"Lets Discuss Your Startup Strategy.",fcd:"Schedule a confidential consultation with our sector specialists.",fc1t:"TALK TO OUR INDUSTRY EXPERTS",fc1h:"/contact",fc2t:"BOOK A CONSULTATION",fc2h:"/book-consultation",ch:[{n:"01.",t:"Fundraising Structure",d:"Structuring financing rounds that protect founder control while satisfying investor governance expectations."},{n:"02.",t:"Cap Table Complexity",d:"Managing dilution and equity structuring across multiple funding rounds and employee grants."},{n:"03.",t:"Regulatory Onboarding",d:"Establishing compliance foundations early enough to avoid costly retrofits at scale."},{n:"04.",t:"Growth vs. Governance",d:"Balancing rapid iteration against the governance rigor investors and regulators increasingly expect."}],sol:[{l:"NAVIGATE",d:"Early-stage regulatory and compliance onboarding."},{l:"STRENGTHEN",d:"Cap table and fundraising governance."},{l:"TRANSFORM",d:"Founder-led decisions into durable structure."},{l:"SCALE",d:"Growth through structured capital deployment."}],pas:["risk-assurance","tax-fiscal-advisory","corporate-law","business-advisory"]},
];

async function run() {
  console.log("Seeding last 6 industries...");
  for (const ind of industries) await upsertIndustry(ind);
  console.log("Done!");
}
run().catch(e => { console.error(e.message || e); process.exit(1); });
