import { neon } from "@neondatabase/serverless";
import { readFileSync } from "fs";
const envFile = readFileSync(".env.local", "utf8");
for (const line of envFile.split("\n")) { const m = line.match(/^([^#][^=]*)=(.*)$/); if (m) process.env[m[1].trim()] = m[2].trim(); }
const sql = neon(process.env.DATABASE_URL);

async function upsertIndustry(ind) {
  const existing = await sql`SELECT id FROM industries WHERE slug=${ind.slug} LIMIT 1`;
  let id;
  if (existing.length > 0) {
    id = existing[0].id;
    await sql`UPDATE industries SET name=${ind.name},sort_order=${ind.so},short_description=${ind.sd},hero_eyebrow=${ind.he},hero_heading=${ind.hh},hero_description=${ind.hd},hero_image_url=${ind.hiu},hero_image_alt=${ind.hia},hero_cta1_text=${ind.hc1t},hero_cta1_href=${ind.hc1h},hero_cta2_text=${ind.hc2t},hero_cta2_href=${ind.hc2h},overview_heading=${ind.oh},overview_quote=${ind.oq},overview_body=${ind.ob},overview_body2=${ind.ob2},challenges_intro=${ind.ci},solutions_heading=${ind.sh},solutions_intro=${ind.si},final_cta_heading=${ind.fch},final_cta_description=${ind.fcd},final_cta1_text=${ind.fc1t},final_cta1_href=${ind.fc1h},final_cta2_text=${ind.fc2t},final_cta2_href=${ind.fc2h},is_published=true,updated_at=NOW() WHERE id=${id}`;
  } else {
    const [r] = await sql`INSERT INTO industries (slug,name,sort_order,short_description,hero_eyebrow,hero_heading,hero_description,hero_image_url,hero_image_alt,hero_cta1_text,hero_cta1_href,hero_cta2_text,hero_cta2_href,overview_heading,overview_quote,overview_body,overview_body2,challenges_intro,solutions_heading,solutions_intro,final_cta_heading,final_cta_description,final_cta1_text,final_cta1_href,final_cta2_text,final_cta2_href,is_published) VALUES (${ind.slug},${ind.name},${ind.so},${ind.sd},${ind.he},${ind.hh},${ind.hd},${ind.hiu},${ind.hia},${ind.hc1t},${ind.hc1h},${ind.hc2t},${ind.hc2h},${ind.oh},${ind.oq},${ind.ob},${ind.ob2},${ind.ci},${ind.sh},${ind.si},${ind.fch},${ind.fcd},${ind.fc1t},${ind.fc1h},${ind.fc2t},${ind.fc2h},true) RETURNING id`;
    id = r.id;
  }

  await sql`DELETE FROM industry_challenges WHERE industry_id=${id}`;
  for (let i=0;i<ind.ch.length;i++) {
    const c=ind.ch[i];
    await sql`INSERT INTO industry_challenges (industry_id,number,title,description,sort_order,is_visible) VALUES (${id},${c.n},${c.t},${c.d},${i},true)`;
  }

  await sql`DELETE FROM industry_solutions WHERE industry_id=${id}`;
  for (let i=0;i<ind.sol.length;i++) {
    const s=ind.sol[i];
    await sql`INSERT INTO industry_solutions (industry_id,label,description,sort_order,is_visible) VALUES (${id},${s.l},${s.d},${i},true)`;
  }

  const pas = await sql`SELECT id,slug FROM practice_areas WHERE is_published=true`;
  const paMap = Object.fromEntries(pas.map(p=>[p.slug,p.id]));
  await sql`DELETE FROM industry_practice_areas WHERE industry_id=${id}`;
  for (let i=0;i<ind.pas.length;i++) {
    const paId=paMap[ind.pas[i]];
    if (paId) await sql`INSERT INTO industry_practice_areas (industry_id,practice_area_id,sort_order) VALUES (${id},${paId},${i}) ON CONFLICT DO NOTHING`;
  }

  console.log("  seeded: " + ind.name + " (id=" + id + ")");
}

const industries = [
  {slug:"manufacturing",name:"Manufacturing",so:1,sd:"Optimizing supply chains and navigating industrial regulation.",he:"INDUSTRIES",hh:"Manufacturing Advisory",hd:"A rigorous, strategic approach to navigating supply chain volatility, industrial compliance, and the operational pressures unique to modern manufacturing.",hiu:"https://images.unsplash.com/photo-1565043666747-69f6646db940?auto=format&fit=crop&w=1200&q=85",hia:"Manufacturing facility",hc1t:"TALK TO OUR INDUSTRY EXPERTS",hc1h:"/contact",hc2t:"EXPLORE RELEVANT SERVICES",hc2h:"/industries/manufacturing#how-we-help",oh:"Understanding Manufacturing",oq:"Resilience in manufacturing is no longer optional — it is the baseline for competing in a volatile global supply chain.",ob:"The current landscape of manufacturing is defined by supply chain fragility, rising input costs, and mounting pressure to modernize production lines without disrupting output.",ob2:"At PSC Global, we recognize that generalized solutions are insufficient. Manufacturers need bespoke frameworks that account for multi-tier supplier risk, labor regulation, and capital-intensive equipment cycles.",ci:"Strategic imperatives dictated by the current industrial and macroeconomic environment.",sh:"Advisory Built Around Your Production Reality",si:"We deploy cross-functional teams combining deep industrial knowledge with specialized technical capabilities.",fch:"Lets Discuss Your Industry.",fcd:"Schedule a confidential consultation with our sector specialists to architect the optimal structural approach for your enterprise.",fc1t:"TALK TO OUR INDUSTRY EXPERTS",fc1h:"/contact",fc2t:"BOOK A CONSULTATION",fc2h:"/book-consultation",ch:[{n:"01.",t:"Supply Chain Fragility",d:"Diversifying supplier bases and building contingency capacity against geopolitical and logistics disruption."},{n:"02.",t:"Regulatory Complexity",d:"Navigating environmental, labor, and trade compliance requirements across multiple manufacturing jurisdictions."},{n:"03.",t:"Capital Intensity",d:"Structuring financing for equipment modernization and automation without overleveraging the balance sheet."},{n:"04.",t:"Workforce Transition",d:"Managing the shift toward automated production while retaining institutional operational knowledge."}],sol:[{l:"NAVIGATE",d:"Cross-border trade and environmental regulation."},{l:"STRENGTHEN",d:"Supply chain resilience and supplier governance."},{l:"TRANSFORM",d:"Production models toward greater automation."},{l:"SCALE",d:"Operations through strategic capital deployment."}],pas:["risk-assurance","tax-fiscal-advisory","corporate-law","business-advisory"]},
  {slug:"infrastructure",name:"Infrastructure",so:2,sd:"Long-term advisory for large-scale capital projects.",he:"INDUSTRIES",hh:"Infrastructure Advisory",hd:"Long-term strategic advisory for large-scale capital projects, balancing public accountability, financing complexity, and multi-decade operational horizons.",hiu:"https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=1200&q=85",hia:"Infrastructure project",hc1t:"TALK TO OUR INDUSTRY EXPERTS",hc1h:"/contact",hc2t:"EXPLORE RELEVANT SERVICES",hc2h:"/industries/infrastructure#how-we-help",oh:"Understanding Infrastructure",oq:"Infrastructure decisions made today set the operational reality for the next thirty years — precision matters at every stage.",ob:"The infrastructure sector is defined by long project horizons, heavy capital requirements, and dense regulatory oversight spanning multiple levels of government.",ob2:"Our teams partner with public and private stakeholders to de-risk large-scale projects, from environmental approvals through to long-term asset management.",ci:"Strategic imperatives dictated by the current infrastructure financing environment.",sh:"Advisory Built Around Long-Horizon Delivery",si:"We deploy cross-functional teams combining project finance expertise with regulatory and operational depth.",fch:"Lets Discuss Your Infrastructure Project.",fcd:"Schedule a confidential consultation with our sector specialists to architect the optimal structural approach for your enterprise.",fc1t:"TALK TO OUR INDUSTRY EXPERTS",fc1h:"/contact",fc2t:"BOOK A CONSULTATION",fc2h:"/book-consultation",ch:[{n:"01.",t:"Project Financing",d:"Structuring public-private partnerships and long-duration debt instruments that survive interest rate cycles."},{n:"02.",t:"Regulatory Approval",d:"Managing multi-jurisdictional environmental and planning approval processes without derailing timelines."},{n:"03.",t:"Cost Overrun Risk",d:"Building contractual and governance safeguards against the inflation and delay risks endemic to megaprojects."},{n:"04.",t:"Long-Term Asset Management",d:"Establishing maintenance and governance frameworks that protect asset value over multi-decade lifecycles."}],sol:[{l:"NAVIGATE",d:"Complex multi-jurisdictional approval processes."},{l:"STRENGTHEN",d:"Project financing and risk-sharing structures."},{l:"TRANSFORM",d:"Asset management for long-term resilience."},{l:"SCALE",d:"Portfolios through structured capital deployment."}],pas:["risk-assurance","tax-fiscal-advisory","corporate-law","business-advisory"]},
  {slug:"real-estate",name:"Real Estate",so:3,sd:"Strategic portfolio management and asset protection.",he:"INDUSTRIES",hh:"Real Estate Advisory",hd:"Strategic portfolio management and asset protection for real estate operators navigating shifting valuations, financing costs, and regulatory pressure.",hiu:"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=85",hia:"Commercial real estate",hc1t:"TALK TO OUR INDUSTRY EXPERTS",hc1h:"/contact",hc2t:"EXPLORE RELEVANT SERVICES",hc2h:"/industries/real-estate#how-we-help",oh:"Understanding Real Estate",oq:"Portfolio resilience in real estate now depends as much on financing structure as it does on location.",ob:"The real estate landscape is defined by rate-sensitive valuations, shifting tenant demand, and tightening regulatory scrutiny over ownership structures.",ob2:"Our teams work directly with asset managers and developers to structure transactions, optimize tax exposure, and manage risk across diversified holdings.",ci:"Strategic imperatives dictated by the current real estate and financing environment.",sh:"Advisory Built Around Portfolio Resilience",si:"We deploy cross-functional teams combining real estate finance expertise with regulatory and tax depth.",fch:"Lets Discuss Your Real Estate Portfolio.",fcd:"Schedule a confidential consultation with our sector specialists to architect the optimal structural approach for your enterprise.",fc1t:"TALK TO OUR INDUSTRY EXPERTS",fc1h:"/contact",fc2t:"BOOK A CONSULTATION",fc2h:"/book-consultation",ch:[{n:"01.",t:"Valuation Volatility",d:"Managing portfolio exposure as interest rate shifts compress or expand asset valuations."},{n:"02.",t:"Regulatory Scrutiny",d:"Navigating tightening disclosure and ownership transparency requirements across jurisdictions."},{n:"03.",t:"Financing Structure",d:"Structuring debt and equity positions that remain viable through rate cycles."},{n:"04.",t:"Portfolio Diversification",d:"Balancing asset class and geographic exposure to reduce concentrated risk."}],sol:[{l:"NAVIGATE",d:"Ownership transparency and disclosure regulation."},{l:"STRENGTHEN",d:"Financing structures across market cycles."},{l:"TRANSFORM",d:"Portfolios toward diversified, resilient holdings."},{l:"SCALE",d:"Acquisitions through structured capital deployment."}],pas:["risk-assurance","tax-fiscal-advisory","corporate-law","business-advisory"]},
  {slug:"aviation",name:"Aviation",so:4,sd:"Navigating complex international aerospace compliance.",he:"INDUSTRIES",hh:"Aviation Advisory",hd:"Navigating complex international aerospace compliance, fleet financing, and operational safety mandates across a highly regulated global sector.",hiu:"https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1200&q=85",hia:"Aviation fleet",hc1t:"TALK TO OUR INDUSTRY EXPERTS",hc1h:"/contact",hc2t:"EXPLORE RELEVANT SERVICES",hc2h:"/industries/aviation#how-we-help",oh:"Understanding Aviation",oq:"Aviation compliance is not a single framework — it is a mesh of overlapping national and international mandates.",ob:"The aviation sector is defined by dense international regulation, capital-intensive fleet cycles, and safety mandates that leave no margin for structural ambiguity.",ob2:"Our teams bring applied experience in cross-border leasing, safety certification pathways, and the fiscal structuring unique to aircraft assets.",ci:"Strategic imperatives dictated by the current aviation regulatory and financing environment.",sh:"Advisory Built Around Regulatory Precision",si:"We deploy cross-functional teams combining aerospace regulatory knowledge with fleet finance expertise.",fch:"Lets Discuss Your Aviation Operations.",fcd:"Schedule a confidential consultation with our sector specialists to architect the optimal structural approach for your enterprise.",fc1t:"TALK TO OUR INDUSTRY EXPERTS",fc1h:"/contact",fc2t:"BOOK A CONSULTATION",fc2h:"/book-consultation",ch:[{n:"01.",t:"International Compliance",d:"Reconciling overlapping national aviation authority requirements across operating regions."},{n:"02.",t:"Fleet Financing",d:"Structuring aircraft leasing and ownership arrangements that optimize tax and liability exposure."},{n:"03.",t:"Safety Certification",d:"Managing certification pathways for new aircraft types and operational expansions."},{n:"04.",t:"Operational Cost Pressure",d:"Balancing fuel, maintenance, and crew costs against competitive route economics."}],sol:[{l:"NAVIGATE",d:"Overlapping international aviation authority regimes."},{l:"STRENGTHEN",d:"Fleet financing and leasing structures."},{l:"TRANSFORM",d:"Operations for long-term certification stability."},{l:"SCALE",d:"Fleets through structured capital deployment."}],pas:["risk-assurance","tax-fiscal-advisory","corporate-law","business-advisory"]},
  {slug:"energy",name:"Energy",so:5,sd:"Advising on the transition to sustainable power models.",he:"INDUSTRIES",hh:"Energy Advisory",hd:"Advising on the transition to sustainable power models while managing the regulatory, financing, and operational complexity of legacy energy assets.",hiu:"https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=1200&q=85",hia:"Renewable energy",hc1t:"TALK TO OUR INDUSTRY EXPERTS",hc1h:"/contact",hc2t:"EXPLORE RELEVANT SERVICES",hc2h:"/industries/energy#how-we-help",oh:"Understanding Energy",oq:"The energy transition is a balance sheet problem as much as it is an engineering one.",ob:"The energy sector is defined by the tension between legacy asset economics and the accelerating shift toward renewable generation and storage.",ob2:"Our teams bring applied experience in project finance, carbon regulation, and the fiscal structuring of both conventional and renewable energy assets.",ci:"Strategic imperatives dictated by the current energy transition and regulatory environment.",sh:"Advisory Built Around Transition Risk",si:"We deploy cross-functional teams combining energy project finance with carbon and regulatory expertise.",fch:"Lets Discuss Your Energy Strategy.",fcd:"Schedule a confidential consultation with our sector specialists to architect the optimal structural approach for your enterprise.",fc1t:"TALK TO OUR INDUSTRY EXPERTS",fc1h:"/contact",fc2t:"BOOK A CONSULTATION",fc2h:"/book-consultation",ch:[{n:"01.",t:"Transition Financing",d:"Structuring capital allocation across legacy assets and renewable generation build-out."},{n:"02.",t:"Carbon Regulation",d:"Navigating evolving emissions frameworks and carbon pricing mechanisms across jurisdictions."},{n:"03.",t:"Grid Integration",d:"Managing the operational complexity of integrating variable renewable generation at scale."},{n:"04.",t:"Stranded Asset Risk",d:"Protecting balance sheet value as legacy assets face accelerated depreciation timelines."}],sol:[{l:"NAVIGATE",d:"Carbon pricing and emissions compliance regimes."},{l:"STRENGTHEN",d:"Financing structures across generation portfolios."},{l:"TRANSFORM",d:"Asset mix toward sustainable generation."},{l:"SCALE",d:"Renewable build-out through structured capital."}],pas:["risk-assurance","tax-fiscal-advisory","corporate-law","business-advisory"]},
  {slug:"banking-finance",name:"Banking & Finance",so:6,sd:"Securing assets in a volatile global regulatory climate.",he:"INDUSTRIES",hh:"Banking & Finance Advisory",hd:"Securing assets and structuring resilient governance frameworks for financial institutions navigating a volatile global regulatory climate.",hiu:"https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=85",hia:"Banking services",hc1t:"TALK TO OUR INDUSTRY EXPERTS",hc1h:"/contact",hc2t:"EXPLORE RELEVANT SERVICES",hc2h:"/industries/banking-finance#how-we-help",oh:"Understanding Banking & Finance",oq:"Regulatory capital requirements are moving faster than most institutions can restructure around them.",ob:"The banking and finance sector is defined by tightening capital adequacy requirements, accelerating digital transformation, and cross-border compliance complexity.",ob2:"Our teams bring applied experience in prudential regulation, digital banking transformation, and the fiscal structuring unique to financial institutions.",ci:"Strategic imperatives dictated by the current financial regulatory environment.",sh:"Advisory Built Around Regulatory Resilience",si:"We deploy cross-functional teams combining prudential regulatory knowledge with digital transformation expertise.",fch:"Lets Discuss Your Banking Challenges.",fcd:"Schedule a confidential consultation with our sector specialists to architect the optimal structural approach for your enterprise.",fc1t:"TALK TO OUR INDUSTRY EXPERTS",fc1h:"/contact",fc2t:"BOOK A CONSULTATION",fc2h:"/book-consultation",ch:[{n:"01.",t:"Capital Adequacy",d:"Structuring balance sheets to satisfy evolving prudential capital requirements."},{n:"02.",t:"Cross-Border Compliance",d:"Reconciling divergent regulatory regimes across operating jurisdictions."},{n:"03.",t:"Digital Transformation",d:"Modernizing core banking infrastructure while maintaining regulatory continuity."},{n:"04.",t:"Financial Crime Risk",d:"Strengthening AML and fraud governance frameworks against increasingly sophisticated threats."}],sol:[{l:"NAVIGATE",d:"Prudential capital and cross-border regulation."},{l:"STRENGTHEN",d:"Governance and financial crime frameworks."},{l:"TRANSFORM",d:"Core infrastructure for digital banking."},{l:"SCALE",d:"Operations through structured capital deployment."}],pas:["risk-assurance","tax-fiscal-advisory","corporate-law","business-advisory"]},
];

async function run() {
  console.log("Seeding first 6 industries...");
  for (const ind of industries) await upsertIndustry(ind);
  console.log("Done!");
}
run().catch(e => { console.error(e.message || e); process.exit(1); });
